version: '3.8'
services: 
  mongo:
    container_name: mongo-contenedor
    image: mongo
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes: 
      - apiDB:/data/db
  api:
    container_name: api-contenedor
    restart: always
    build: ./server
    ports: 
      - "8081:8081"
    depends_on: 
      - mongo
  client:
    container_name: client-contenedor
    restart: always
    build: ./client
    ports: 
      - "8080:8080"
    depends_on: 
      - api


volumes: 
  apiDB:
